---
# For a full list of ovirt_vms parameters, visit:
# http://docs.ansible.com/ansible/latest/ovirt_vms_module.html

# RHV Auth parameters
# engine_url: "{{ lookup('env', 'OVIRT_URL') }}"
# engine_user: "{{ lookup('env', 'OVIRT_USERNAME') }}"
# engine_password: "{{ lookup('env', 'OVIRT_PASSWORD') }}"
# engine_cafile: "{{ lookup('env', 'OVIRT_CAFILE') }}"

engine_url: "{{ lookup('env', 'OVIRT_URL') }}"
engine_user: "{{ lookup('env', 'OVIRT_USERNAME') }}"
engine_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64346561363331306139653037363834323831623934353165356363393737396364616464343030
          3833383338636666393534353936653234333561386433660a393437373730623264333938633833
          38303830653665613035616263313936383935313566636530663363646566313432653731353334
          3338643532373231610a323063626438323832346237343937313763626433653237633633316434
          6435

template:
cluster:

# vm guest parameters
vm_names:
memory: 1GiB
cpu_cores: 1
cpu_sockets: 1
operating_system: rhel_7x64
type: server
description:
comment: Provisioned via Ansible
state: poweredon
wait_for_ip_address: true
remove_vms_on_error: true

## vm networking parameters
nics:
  - name: "{{ network_0_name | default('nic1') }}"
    profile_name: "{{ network_0_vlan | default('ovirtmgmt') }}"
    ### interface - (virtio, e1000, rtl8139)
    # interface: "{{ network_0_interface | default('virtio') }}"

## vm disk parameters
# disks:
#   - name: "{{ disk_0_name | default('disk1') }}"
#     bootable: "{{ disk_0_bootable | default(true) }}"

# asynchronous parameters
async_wait: 3600
async_poll: 0
async_retries: 100

# setup retry variables
wait_for_ip_retries: 20
wait_for_ip_delay: 10

# enable extra debugging
verbose: false
